r"""Build the shippable release folder and zip. Phase 6.

    python tools/build_release.py            # freeze + assemble + hash + zip
    python tools/build_release.py --no-freeze # skip PyInstaller (docs-only rebuild)

Produces  dist/K1-Area-Map-Fixes-<version>/  and the matching .zip.

Two deliberate choices, both from docs/RELEASE_PLAN.md section 5:

  * --onedir, not --onefile. A single self-extracting exe is a known antivirus
    heuristic trigger and we already own a second one (we grow a PE section).
  * The Python source ships alongside the frozen build, and every file's
    sha256 is published, so a user who will not run an unsigned exe can run
    install.py directly and still verify what they got.

The frozen build gets BOTH entry points in one folder, because Install.bat and
Uninstall.bat look for Patcher\K1AreaMapFixes.exe and
Patcher\K1AreaMapFixes-Revert.exe side by side. PyInstaller only does that from
a .spec with two Analysis/EXE pairs feeding one COLLECT, which is what
write_spec() below emits.

The player sees three files and two folders: Install.bat, Uninstall.bat,
README.txt, Patcher\ and "More info"\. Everything that is real but secondary -
licence, hashes, the technical and compatibility notes, the Python source -
lives under "More info" rather than in the first impression.
"""
from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATCHER = os.path.join(ROOT, "patcher")
TOOLS = os.path.join(ROOT, "tools")
DIST = os.path.join(ROOT, "dist")
BUILD = os.path.join(ROOT, "staging", "pyinstaller")

sys.path.insert(0, PATCHER)
from k1amf import PRODUCT, __version__          # noqa: E402

NAME = "K1-Area-Map-Fixes-%s" % __version__
FROZEN_DIR = "Patcher"
EXTRAS_DIR = "More info"

# The tools/ modules the patcher imports at runtime. _toolpath.py puts this
# directory on sys.path; PyInstaller pulls them in as hidden imports because
# nothing imports them by a literal name it can see.
# backup_paths is imported by three of these; leaving it out silently breaks
# `python source/install.py`, which the README offers as the way to avoid
# running an unsigned exe. PyInstaller found it on its own, so the frozen
# build worked and the source did not.
RUNTIME_TOOLS = ("hires_patch", "pe_space", "note_table_patch", "gff",
                 "backup_paths")

# README and the launchers stay at the top level - they are the only things a
# player needs to see. Everything else is real but secondary, so it goes one
# folder down rather than into the first impression.
TOP_DOCS = ("README.txt",)
EXTRA_DOCS = ("COMPATIBILITY.txt", "TROUBLESHOOTING.txt", "TECHNICAL.txt")


def keystone_dll():
    """keystone.dll, and where it has to sit in the frozen build.

    note_table_patch assembles the match routine with keystone at install time,
    so the assembler is a runtime dependency, not a build-time one.
    PyInstaller has a hook for capstone but not for keystone: it collects
    keystone's .py files and silently leaves keystone.dll behind. keystone.py
    looks for the DLL beside its own __file__ first and only falls back to
    distutils.sysconfig - removed from the stdlib in Python 3.12 - if that
    fails, so a build missing the DLL dies at the fallback with a confusing
    "No module named 'distutils'". Put the DLL where it looks first.
    """
    import keystone as _ks
    src = os.path.join(os.path.dirname(_ks.__file__), "keystone.dll")
    if not os.path.isfile(src):
        raise SystemExit("keystone.dll not found next to %s" % _ks.__file__)
    return src

# note_table_patch.build() imports map_calibration, which pulls in PyKotor and
# therefore numpy and Pillow - 40 MB of a 63 MB build, for a code path the
# shipped patcher never takes (it writes the frozen table instead of
# re-deriving keys). PyInstaller follows the import statically anyway, so name
# them out. tools/verify_release.py proves the exclusion is safe by running the
# frozen build end to end.
# Kept deliberately narrow: hashlib (sha256, used everywhere) reaches into
# _hashlib/libcrypto, so ssl and its neighbours are NOT excluded.
EXCLUDES = ("numpy", "PIL", "Pillow", "pykotor", "map_calibration",
            "setuptools", "pkg_resources", "tkinter")


def write_spec(path):
    """A two-entry-point onedir spec. Both exes land in one COLLECT folder."""
    spec = '''# -*- mode: python ; coding: utf-8 -*-
# Generated by tools/build_release.py - do not edit by hand.
import os

PATCHER = r"{patcher}"
TOOLS = r"{tools}"
HIDDEN = {hidden!r}
EXCLUDES = {excludes!r}
PATHEX = [PATCHER, TOOLS]
DATAS = [(os.path.join(PATCHER, "data"), "data")]
# keystone.dll goes into keystone/ so keystone.py's first search path finds it.
BINARIES = [(r"{ksdll}", "keystone")]

a_install = Analysis([os.path.join(PATCHER, "install.py")], pathex=PATHEX,
                     datas=DATAS, binaries=BINARIES, hiddenimports=HIDDEN,
                     excludes=EXCLUDES, noarchive=False)
a_revert = Analysis([os.path.join(PATCHER, "revert.py")], pathex=PATHEX,
                    datas=DATAS, binaries=BINARIES, hiddenimports=HIDDEN,
                    excludes=EXCLUDES, noarchive=False)

MERGE((a_install, "install", "install"), (a_revert, "revert", "revert"))

pyz_install = PYZ(a_install.pure)
pyz_revert = PYZ(a_revert.pure)

exe_install = EXE(pyz_install, a_install.scripts, [], exclude_binaries=True,
                  name="K1AreaMapFixes", console=True, upx=False)
exe_revert = EXE(pyz_revert, a_revert.scripts, [], exclude_binaries=True,
                 name="K1AreaMapFixes-Revert", console=True, upx=False)

coll = COLLECT(exe_install, a_install.binaries, a_install.datas,
               exe_revert, a_revert.binaries, a_revert.datas,
               strip=False, upx=False, name="{frozen}")
'''.format(patcher=PATCHER, tools=TOOLS, hidden=list(RUNTIME_TOOLS),
           excludes=list(EXCLUDES), ksdll=keystone_dll(), frozen=FROZEN_DIR)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(spec)
    return path


def freeze(out_dir):
    os.makedirs(BUILD, exist_ok=True)
    spec = write_spec(os.path.join(BUILD, "K1AreaMapFixes.spec"))
    cmd = [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
           "--distpath", out_dir, "--workpath", os.path.join(BUILD, "work"),
           spec]
    print("$ " + " ".join(cmd))
    subprocess.check_call(cmd, cwd=ROOT)

    for exe in ("K1AreaMapFixes.exe", "K1AreaMapFixes-Revert.exe"):
        p = os.path.join(out_dir, FROZEN_DIR, exe)
        if not os.path.isfile(p):
            raise SystemExit("PyInstaller did not produce %s" % p)
    print("  frozen: both entry points present")


def copy_source(dest):
    """Ship the source the frozen build was made from, and only that."""
    os.makedirs(dest, exist_ok=True)
    # selftest.py is deliberately NOT shipped: it needs a development fixture
    # (an official-chain exe under staging/) that no player has, so it can only
    # ever fail for them and look like a broken mod.
    for name in ("install.py", "revert.py"):
        shutil.copy2(os.path.join(PATCHER, name), dest)
    shutil.copytree(os.path.join(PATCHER, "k1amf"), os.path.join(dest, "k1amf"),
                    ignore=shutil.ignore_patterns("__pycache__"))
    shutil.copytree(os.path.join(PATCHER, "data"), os.path.join(dest, "data"))
    tools_dest = os.path.join(dest, "tools")
    os.makedirs(tools_dest, exist_ok=True)
    for mod in RUNTIME_TOOLS:
        shutil.copy2(os.path.join(TOOLS, mod + ".py"), tools_dest)


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def write_sums(root):
    """sha256 of every shipped file, relative paths, sorted, sums file last."""
    lines = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for fn in sorted(filenames):
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            if rel == EXTRAS_DIR + "/SHA256SUMS.txt":
                continue
            lines.append("%s  %s" % (sha256(full), rel))
    out = os.path.join(root, EXTRAS_DIR, "SHA256SUMS.txt")
    with open(out, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("%s %s - sha256 of every file in this release.\n"
                 "Verify on Windows with:\n"
                 "    certutil -hashfile <file> SHA256\n\n" % (PRODUCT, __version__))
        fh.write("\n".join(lines) + "\n")
    return len(lines)


def main(argv):
    do_freeze = "--no-freeze" not in argv
    out = os.path.join(DIST, NAME)
    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(out)

    print("%s %s -> %s" % (PRODUCT, __version__, out))

    extras = os.path.join(out, EXTRAS_DIR)
    os.makedirs(extras)
    for name in TOP_DOCS + ("Install.bat", "Uninstall.bat"):
        shutil.copy2(os.path.join(PATCHER, name), out)
    for name in EXTRA_DOCS:
        shutil.copy2(os.path.join(PATCHER, name), extras)
    shutil.copy2(os.path.join(ROOT, "LICENSE"), extras)
    print("  README and launchers at the top level, the rest under %r" % EXTRAS_DIR)

    copy_source(os.path.join(extras, "source"))
    print("  source copied")

    if do_freeze:
        freeze(out)
    else:
        print("  --no-freeze: skipping PyInstaller")

    n = write_sums(out)
    print("  %s/SHA256SUMS.txt: %d files" % (EXTRAS_DIR, n))

    zip_path = out + ".zip"
    if os.path.isfile(zip_path):
        os.remove(zip_path)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for dirpath, dirnames, filenames in os.walk(out):
            dirnames.sort()
            for fn in sorted(filenames):
                full = os.path.join(dirpath, fn)
                z.write(full, os.path.join(NAME, os.path.relpath(full, out)))
    print("  %s  (%.1f MB)" % (zip_path, os.path.getsize(zip_path) / 1e6))
    print("  zip sha256 %s" % sha256(zip_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
